<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<Target Name="CopyToAppPlugins" AfterTargets="Build">
		<ItemGroup>
			<_dll Include="$(TargetPath)" />
		</ItemGroup>
		<MakeDir Directories="$(SolutionDir)Warframe Progress Tracker\bin\$(Configuration)\net8.0-windows\Plugins" Condition="Exists('$(SolutionDir)')" />
		<Copy SourceFiles="@(_dll)" DestinationFolder="$(SolutionDir)Warframe Progress Tracker\bin\$(Configuration)\net8.0-windows\Plugins" SkipUnchangedFiles="true" Condition="Exists('$(SolutionDir)')" />
	</Target>

</Project>
