<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Warframe_Progress_Tracker</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.8" />
    <PackageReference Include="Microsoft.Playwright" Version="1.55.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PDFsharp" Version="6.2.2" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.1" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mastery\Warframe.Tracker.Mastery.csproj" />
    <ProjectReference Include="..\Warframe.Tracker.Filters\Warframe.Tracker.Filters.csproj" />
  </ItemGroup>

</Project>
